---
# handlers file for ./provision/roles/log-role
- name: restart_systemd-journal-remote
  systemd:
    name: systemd-journal-remote
    state: restarted
    daemon_reload: yes

- name: restart_auditd
  shell: |
    systemctl daemon-reload
    service auditd restart
  args:
    executable: /bin/bash
    warn: no
