all:
  hosts:
    pxeserver:
      ansible_port: 2222
      ansible_private_key_file: .vagrant/machines/pxeserver/virtualbox/private_key
    pxeclient:
      ansible_port: 2200
      ansible_private_key_file: .vagrant/machines/pxeclient/virtualbox/private_key
  vars:
    ansible_host: 127.0.0.1

