---
- hosts: all # part running on all hosts
  become: true
  
  tasks:
    #  - debug:
    #  msg:
    #  - "{{ user }}"
    #  - "{{ group }}"

  - name: Install epel-release # переведём синтаксис yum из deprecated
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - epel-release

  - name: Install requied packages
    yum:
      name: '{{ item }}'
      state: present
    when: packages is defined
    loop: '{{ packages }}'

  - name: Enable services
    systemd:
      state: '{{ item.state }}'
      name: '{{ item.name }}'
      enabled: '{{ item.enabled }}'
      daemon_reload: yes
    when: services is defined
    with_items:
      - '{{ services }}'      

- hosts: inetRouter inetRouter2
  become: true
  roles:
    - inetrouter-role

- hosts: centralRouter 
  become: true
  roles:
    - router-role

- hosts: centralServer
  become: true
  roles:
    - server-role