---
# tasks file for provision/postgres_install

- name: Install psycopg2
  become: yes
  shell: |
    pip3 install psycopg2==2.7.5 --ignore-installed
  
- name: disable default module postgre 
  become: yes
  shell: |
    yum -y module disable postgresql
    yum -y clean all


- name: Install PostgreSQL repo
  yum:
    name: "{{ postgresql_repo }}"
    state: present

- name: Install PostgreSQL packages
  package:
    name: "{{ packages }}"
    state: present
