---
routes:
  - dev: eth1
    route: '10.10.0.0/24 10.10.255.6'
internal_nh: 10.10.255.6

packages:
  - iptables-services
  - tcpdump

services:
  - name: firewalld
    state: stopped
    enabled: no

  - name: iptables
    state: started
    enabled: yes