---
# handlers file for provision/roles/inetrouter-role
- name: restart_iptables
  systemd:
    name: iptables
    state: restarted

- name: restart_sshd
  systemd:
    name: sshd
    state: restarted