---
# tasks file for provision/roles/backup-server-role

- name: Check directory exists
  ansible.builtin.stat:
    path: "{{ repo_path }}"
  register: repo_path_exists

- name: Create partition, filesystem and mount point
  shell: |
    echo -e "o\nn\np\n1\n\n\nw" | fdisk /dev/sdb
    mkfs.xfs /dev/sdb1
    mkdir "{{ repo_path }}"
    mount /dev/sdb1 "{{ repo_path }}"
  args:
    warn: no
  when: repo_path_exists.stat.exists == False

- name: Add backup user group 
  group: 
    name: "{{ group }}" 
    state: present    

- name: Add user backup
  user:
    name: "{{ user }}"
    group: "{{ group }}"  
    home: "{{ home }}"
    createhome: yes  
    shell: /bin/bash  
    state: present

- name: Recursively change ownership of a directory
  file:
    path: "{{ repo_path }}"
    state: directory
    recurse: yes
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0755'

#- debug:
#    msg: "{{ hostvars['client'].master_public_key.stdout }}"

- name: Add client public key to server
  authorized_key:
    user: "{{ user }}"
    key: "{{ hostvars['backupclient'].main_public_key.stdout }}"

