version: "3"

services:
  nginx:
    image: stavdock/nginx:custom
    container_name: nginx
    depends_on: 
        - phpfpm
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - front_end
      
  phpfpm:
    container_name: phpfpm
    image: bitnami/php-fpm:8.1.10
    volumes:
      - ./www:/var/www/html
    ports:
      - 9000:9000
    networks:
      - front_end

networks:
  front_end:
