---
# tasks file for provision/flask-role

#- name: Upgrade pip
#  pip:
#    name: pip
#    state: latest
#    executable: pip2.7

#- name: Install virtualenv
#  pip:
#    name: 
#      - virtualenv
#    state: present
#    executable: pip2.7

- name: Create a directory for app
  file:
    path: /opt/dweb
    state: directory
    mode: 0755

- name: Copy files of app
  copy:
    src: "dweb/{{ item }}"
    dest: "/opt/dweb/{{ item }}"
  loop:
    - dweb.py
    - wsgi.py
    - dweb.ini
    - requirements.txt
  
- name: Initiate virtualenv
  pip: 
    virtualenv: /opt/dweb/dweb_env
    virtualenv_python: python3
    requirements: /opt/dweb/requirements.txt

- name: Change ownership of app directory
  file:
    path: /opt/dweb
    state: directory
    recurse: yes
    owner: nginx
    group: nginx

- name: Copy systemd unit file
  copy:
    src: dweb.service
    dest: /etc/systemd/system/dweb.service

- name: Run systemd unit of app
  systemd:
    name: dweb
    state: started
    enabled: yes
    daemon_reload: yes

- name: Modify file labels for the flask directory
  command: "{{ item }}" 
  with_items:
    - semanage fcontext -a -t httpd_sys_rw_content_t /opt/dweb(/.*)?
    - restorecon -Rv /opt/dweb/

- name: Copy nginx config for a Flask
  copy:
    src: flask.conf
    dest: /etc/nginx/conf.d/flask.conf
    owner: root
    group: root
    mode: '0644'
    force: yes
  notify: Restart_nginx 


