# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
  :r1 => {
        :box_name => "ubuntu/focal64",
        :ip_addr => '10.10.11.151',
        # VM CPU count
        :cpus => 1,
        # VM RAM size (Mb)
        :memory => 1024,
        :net => [
                   {ip: '10.10.1.1', adapter: 2, netmask: "255.255.255.248", virtualbox__intnet: "link1"},
            #       {ip: '10.10.10.1', adapter: 4, netmask: "255.255.255.248", virtualbox__intnet: "net0"},
                   {ip: '10.10.2.1', adapter: 3, netmask: "255.255.255.248", virtualbox__intnet: "link2"}
                ]

  },
  :r2 => {
        :box_name => "ubuntu/focal64",
        :ip_addr => '10.10.11.152',
        # VM CPU count
        :cpus => 1,
        # VM RAM size (Mb)
        :memory => 1024,
        :net => [
                   {ip: '10.10.1.2', adapter: 2, netmask: "255.255.255.248", virtualbox__intnet: "link1"},
                   {ip: '10.10.20.2', adapter: 4, netmask: "255.255.255.248", virtualbox__intnet: "net1"},
                   {ip: '10.10.3.2', adapter: 3, netmask: "255.255.255.248", virtualbox__intnet: "link3"}
                ]

},
  :r3 => {
        :box_name => "ubuntu/focal64",
        :ip_addr => '10.10.11.153',
        # VM CPU count
        :cpus => 1,
        # VM RAM size (Mb)
        :memory => 1024,
        :net => [
                   {ip: '10.10.2.3', adapter: 2, netmask: "255.255.255.248", virtualbox__intnet: "link2"},
                   {ip: '10.10.30.3', adapter: 4, netmask: "255.255.255.248", virtualbox__intnet: "net2"},
                   {ip: '10.10.3.3', adapter: 3, netmask: "255.255.255.248", virtualbox__intnet: "link3"}
                ]

 },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
    # Disable synced folder
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end

        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provider "virtualbox" do |v|
          # Set VM RAM size and CPU count
          v.memory = boxconfig[:memory]
          v.cpus = boxconfig[:cpus]
        end

        box.vm.provision "shell", inline: <<-SHELL
        	timedatectl set-timezone Europe/Moscow
		      mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
       case boxname.to_s
         when "r3"
            box.vm.provision "ansible" do |ansible|
#           ansible.verbose = "vv"
            ansible.playbook = "provision/playbook.yml"
            ansible.become = "true"
            ansible.limit = "all"
         end
        end

      end
  end
end

