# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
:inetRouter => {
        :box_name => "centos/7",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                   {ip: '10.10.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                ]
  },
  :centralRouter => {
        :box_name => "centos/7",
        :net => [
                   {ip: '10.10.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {ip: '10.10.0.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "directors-net"},
                   {ip: '10.10.0.33', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "officehw-net"},
                   {ip: '10.10.0.65', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "wifi-net"},
                   {ip: '10.10.0.17', adapter: 6, netmask: "255.255.255.252", virtualbox__intnet: "office1-net"},
                   {ip: '10.10.0.21', adapter: 7, netmask: "255.255.255.252", virtualbox__intnet: "office2-net"},
                ]
  },
  
  :centralServer => {
        :box_name => "centos/7",
        :net => [
                   {ip: '10.10.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "directors-net"},
                   {adapter: 3, auto_config: false, virtualbox__intnet: true},
                   {adapter: 4, auto_config: false, virtualbox__intnet: true},
                ]
  },
  :office1Router => {
      :box_name => "centos/7",
      :net => [
                   {ip: '10.10.0.18', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "office1-net"},
                   {ip: '10.10.2.1', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "dev1-net"},
                   {ip: '10.10.2.65', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "testservers1-net"},
                   {ip: '10.10.2.129', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "managers1-net"},
                   {ip: '10.10.2.193', adapter: 6, netmask: "255.255.255.192", virtualbox__intnet: "officehw1-net"},
              ]
   },
  :office1Server => {
    :box_name => "centos/7",
    :net => [
                   {ip: '10.10.2.66', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "testservers1-net"},
                   {adapter: 3, auto_config: false, virtualbox__intnet: true},
                   {adapter: 4, auto_config: false, virtualbox__intnet: true},
                   ]
   },
  :office2Router => {
      :box_name => "centos/7",
      :net => [
                   {ip: '10.10.0.22', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "office2-net"},
                   {ip: '10.10.1.1', adapter: 3, netmask: "255.255.255.128", virtualbox__intnet: "dev2-net"},
                   {ip: '10.10.1.129', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "testservers2-net"},
                   {ip: '10.10.1.193', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "officehw2-net"},
              ]
   },
  :office2Server => {
    :box_name => "centos/7",
    :net => [
                   {ip: '10.10.1.130', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "testservers2-net"},
                   {adapter: 3, auto_config: false, virtualbox__intnet: true},
                   {adapter: 4, auto_config: false, virtualbox__intnet: true},
                   ]
   },

}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
    # Disable synced folder
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
        	timedatectl set-timezone Europe/Moscow
#		yum install -y policycoreutils-python \
#               bash-completion \
#		bash-completion-extras \ 
#		vim-enhanced 
		mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
          when "office2Server"
            box.vm.provision "ansible" do |ansible|
            ansible.verbose = "vvv"
            ansible.playbook = "provision/playbook.yml"
            ansible.become = "true"
            ansible.limit = "all"
          end
        end

      end
  end
end

