# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
  :testbash => {
        :box_name => "centos/7",
        :box_version => "1804.02",
        :ip_addr => '10.10.10.101',
        }
    }

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "200"]
          end
          
          box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh
            cp ~vagrant/.ssh/auth* ~root/.ssh
            #copy bash script and log file
            yum install epel-release -y
            #install bash complition and mail sender
            yum install -y bash-completion bash-completion-extras vim-enhanced setools-console mailx
            

          SHELL
    
      end
  end
end

