---
master_ip: 10.10.11.150
slave_ip: 10.10.11.151
backup_ip: 10.10.11.152
postgresql_version: "11"
postgresql_service: postgresql-11
postgresql_bin_path: "/usr/pgsql-11/bin"
postgresql_data_dir: "/var/lib/pgsql/11/data"
postgresql_config_path: "/var/lib/pgsql/11/data"
postgresql_repo: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
physical_replication_slot: standby_slot
replica_username: replica
replica_password: Pass@Word@Rep
barman_username: barman
barman_password: Pass@Word@Bar
streaming_barman: streaming_barman
streaming_barman_password: Pass@Word@Str
packages:
  - postgresql11
  - postgresql11-server
  - postgresql11-contrib
  - unzip
