---
# defaults file for ipaserver

### basic ###
ipaserver_no_host_dns: no
### server ###
ipaserver_setup_adtrust: no
ipaserver_setup_kra: no
ipaserver_setup_dns: no
ipaserver_no_hbac_allow: no
ipaserver_no_pkinit: no
ipaserver_no_ui_redirect: no
ipaserver_mem_check: yes
### ssl certificate ###
### client ###
ipaclient_mkhomedir: no
ipaclient_no_ntp: no
#ipaclient_ssh_trust_dns: no
#ipaclient_no_ssh: no
#ipaclient_no_sshd: no
#ipaclient_no_dns_sshfp: no
### certificate system ###
ipaserver_external_ca: no
### dns ###
ipaserver_allow_zone_overlap: no
ipaserver_no_reverse: no
ipaserver_auto_reverse: no
ipaserver_no_forwarders: no
ipaserver_auto_forwarders: no
ipaserver_no_dnssec_validation: no
### ad trust ###
ipaserver_enable_compat: no
ipaserver_setup_ca: yes
### packages ###
ipaserver_install_packages: yes
### firewalld ###
ipaserver_setup_firewalld: yes

### additional ###
ipaserver_copy_csr_to_controller: no

### uninstall ###
ipaserver_ignore_topology_disconnect: no
ipaserver_ignore_last_of_role: no
ipaadmin_password: ADMPassword1
ipadm_password: DMPassword1
ipaserver_domain: otus.lab
ipaserver_realm: OTUS.LAB
ipa_user_add: ipa user-add director --first="Albus" --last="Dumbledor" --cn="Albus Dumbledor" --sshpubkey="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDa5VtW8RY6mUmE7SwOtF0VaVFDR7rYwo+R8Ww8gGWCHu/IFPU2Jieqnag3MT0ZjEbi56IvWzQeamo2oYs7Ulw/t4vXfZU+fuIXs09TOXZVZdF/IgqP+WAmOIDFiwgB6z/XLFo84dTtocY2rJ5eYP3l94ELXrj391wC5HcemDy7yds58DGPl4I/KAzQpGvfIlyNhoHdMQcJOHiy7eDjlWOxbZOu5q0VPXUnmSZdfc9rXaGTWcJx2D9GXUMgwhD9UMFq9HDWtfJdNE1dzDvrIe3fWBiG1tyRaX/+W9URwBQ+nD9pxinNPbc/FFEMSdDAkULgnhJUdmUlznL6KJKbiMyMdrVuLEkEs4CKkC3MsrwSfLTyuzJizSzZEzo/j0uR5cFP6/GJQDwiNf100JfCuj7pXA8G4jkiwZGKhVajiSZBXTIsq+hZU3B3py4iLVCe6y6vTVrcjNdK0TAz1WVyyphmkcAwRXCs/ldg5GjoIMEsZb+mgbyPUjLoLSaNIjM288k= appuser" --password="123RTYdsa" --shell="/bin/bash"
ipa_add_to_group: ipa group-add-member admins --users=director