# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-8.4"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "vv"
    ansible.playbook = "provision/playbook.yml"
    ansible.become = "true" 
 end

  config.vm.provider "virtualbox" do |v|
	  v.memory = 512
  end

  config.vm.define "ns01" do |ns01|
    ns01.vm.network "private_network", ip: "10.10.50.10", virtualbox__intnet: "dns"
    ns01.vm.hostname = "ns01"
  end

  config.vm.define "ns02" do |ns02|
    ns02.vm.network "private_network", ip: "10.10.50.11", virtualbox__intnet: "dns"
    ns02.vm.hostname = "ns02"
  end

  config.vm.define "client" do |client|
    client.vm.network "private_network", ip: "10.10.50.15", virtualbox__intnet: "dns"
    client.vm.hostname = "client"
  end

  config.vm.define "client2" do |client|
    client.vm.network "private_network", ip: "10.10.50.22", virtualbox__intnet: "dns"
    client.vm.hostname = "client2"
  end

end
