all:
  hosts:
    ipaserver:
      ansible_port: 2222
      ansible_private_key_file: .vagrant/machines/ipaserver/virtualbox/private_key
    ipaclient:
      ansible_port: 2200
      ansible_private_key_file: .vagrant/machines/ipaclient/virtualbox/private_key
  vars:
    ansible_host: 127.0.0.1
