---
- hosts: all # part running on all hosts
  become: true
  
  tasks:
  
  - name: add gpg frrouting.org 
    apt_key:
      url: "https://deb.frrouting.org/frr/keys.asc" 
      state: present      
  - name: add frr repo 
    apt_repository:
      repo: 'deb https://deb.frrouting.org/frr {{ ansible_distribution_release }} frr-stable'
      state: present
      
- hosts: all
  become: true
  roles:
    - router-role

