all:
  hosts:
    web:
      ansible_port: 2222
      ansible_private_key_file: .vagrant/machines/web/virtualbox/private_key
    log:
      ansible_port: 2200
      ansible_private_key_file: .vagrant/machines/log/virtualbox/private_key
  vars:
    ansible_host: 127.0.0.1

