---
# tasks file for provision/create_test_db
- name: Remove demo database if exists
  postgresql_db:
    name: demo
    state: absent
  become: yes
  become_user: postgres

- name: Get demo database
  unarchive:
    #src: https://edu.postgrespro.ru/demo_small.zip
    src: demo_small.zip
    dest: /var/tmp
    #remote_src: yes
    remote_src: no

- name: Load demo database
  become: yes 
  become_user: postgres
  shell: psql -f /var/tmp/demo_small.sql
