---
# tasks file for provision/roles/router-role
- name: Set ip forwarding on in /proc and in the sysctl file and reload if necessary
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Remove default from eth0
  shell: nmcli connection modify System\ eth0 ipv4.never-default yes && nmcli connection up System\ eth0

- name: Setup static routes centralRouter
  shell: "nmcli connection modify System\\ {{ item.dev }} +ipv4.routes \"{{ item.route }}\" && nmcli connection up System\\ {{ item.dev }}"
  loop: "{{ routes }}"
  when: "'centralRouter' in inventory_hostname"

- name: Setup default route
  shell: "nmcli connection modify System\\ {{ item.dev }} ipv4.gateway {{ item.nh }} && nmcli connection up System\\ {{ item.dev }}"
  with_items: 
    - "{{ gw }}"
